# ============================================================
# _common.ps1 — shared helpers for the deployment scripts.
#
# WHY a shared file: every script needs the same .env loader and the same
# "fail loud" behavior. Centralizing avoids drift between scripts.
# ============================================================

# Stop on the first uncaught error. Deployment scripts should never limp along
# after a failed step and leave half-configured resources.
$ErrorActionPreference = 'Stop'

# Resolve the repo root regardless of where the script is invoked from.
# $PSScriptRoot is <repo>\scripts, so the parent is the repo root.
$script:RepoRoot = Split-Path -Parent $PSScriptRoot

function Import-DotEnv {
    <#
    .SYNOPSIS
      Loads KEY="value" pairs from a .env-style file into process env vars.
    .DESCRIPTION
      Ignores blank lines and comments. Strips surrounding quotes and any
      trailing "# inline comment" that follows a quoted value. Missing files
      are skipped silently so .env.derived is optional on the first run.
    #>
    param(
        [Parameter(Mandatory)] [string] $Path
    )

    if (-not (Test-Path $Path)) {
        Write-Verbose "Skipping missing env file: $Path"
        return
    }

    foreach ($line in Get-Content -LiteralPath $Path) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }

        $idx = $trimmed.IndexOf('=')
        if ($idx -lt 1) { continue }

        $name = $trimmed.Substring(0, $idx).Trim()
        $value = $trimmed.Substring($idx + 1).TrimStart()

        if ($value.StartsWith('"') -or $value.StartsWith("'")) {
            # Quoted value: take everything up to the matching closing quote and
            # DISCARD any trailing inline comment (e.g.  FOO="bar"  # note).
            $quote = $value[0]
            $end = $value.IndexOf($quote, 1)
            if ($end -ge 1) {
                $value = $value.Substring(1, $end - 1)
            }
            else {
                $value = $value.Substring(1)  # unterminated quote; take the rest
            }
        }
        else {
            # Unquoted value: strip an inline comment starting at the first '#'.
            $hashIdx = $value.IndexOf('#')
            if ($hashIdx -ge 0) { $value = $value.Substring(0, $hashIdx) }
            $value = $value.Trim()
        }

        [System.Environment]::SetEnvironmentVariable($name, $value, 'Process')
    }
}

function Initialize-Env {
    <#
    .SYNOPSIS
      Loads .env then .env.derived (derived overrides base) from the repo root.
    #>
    Import-DotEnv -Path (Join-Path $script:RepoRoot '.env')
    Import-DotEnv -Path (Join-Path $script:RepoRoot '.env.derived')
}

function Assert-EnvVar {
    <#
    .SYNOPSIS
      Fails fast if a required env var is missing/empty.
    #>
    param([Parameter(Mandatory)] [string[]] $Names)
    foreach ($n in $Names) {
        $val = [System.Environment]::GetEnvironmentVariable($n, 'Process')
        if ([string]::IsNullOrWhiteSpace($val)) {
            throw "Required environment variable '$n' is not set. Check your .env / .env.derived."
        }
    }
}

function Set-DerivedVar {
    <#
    .SYNOPSIS
      Upserts a KEY="value" line into .env.derived (idempotent) and updates the
      current process so later steps in the same run see the new value.
    #>
    param(
        [Parameter(Mandatory)] [string] $Name,
        [Parameter(Mandatory)] [AllowEmptyString()] [string] $Value
    )

    $derivedPath = Join-Path $script:RepoRoot '.env.derived'
    if (-not (Test-Path $derivedPath)) {
        New-Item -ItemType File -Path $derivedPath -Force | Out-Null
        Set-Content -LiteralPath $derivedPath -Value @(
            '# ============================================================',
            '# .env.derived — AUTO-GENERATED by scripts. Do not hand-edit.',
            '# Contains outputs captured from Bicep + Function deploy.',
            '# ============================================================'
        )
    }

    $line = "$Name=`"$Value`""
    $content = Get-Content -LiteralPath $derivedPath
    if ($content -match "^\s*$([regex]::Escape($Name))\s*=") {
        # Replace existing line -> idempotent re-runs.
        $content = $content -replace "^\s*$([regex]::Escape($Name))\s*=.*$", $line
        Set-Content -LiteralPath $derivedPath -Value $content
    }
    else {
        Add-Content -LiteralPath $derivedPath -Value $line
    }

    [System.Environment]::SetEnvironmentVariable($Name, $Value, 'Process')
    Write-Host "  captured $Name" -ForegroundColor DarkGray
}

function Assert-LastExit {
    param([string] $What = 'command')
    if ($LASTEXITCODE -ne 0) {
        throw "$What failed with exit code $LASTEXITCODE."
    }
}
